### ISSUE TITLE
Lots of Failed downloads when downloading from CrunchyRoll

### ISSUE THREAD

**Issue by Ghouls313-2-810** [justin025/onthespot#144]
### Operating System

Windows

### Bug Description

i'm getting a lot of failed downloads in regards to downloading from crunchyroll. no matter if i download the app or use the browser, it doesn't download fully. (btw, if this isn't a bug. i apologize in advance)

**Comment by justin025** [comment]
Could you provide further info? Please attach logs available at %localappdata%/Temp/onthespot/logs

**Comment by Ultra-Meloncrafter** [comment]
Same Problem here, every download from CR just fails

**Comment by justin025** [comment]
If you don't send logs i cannot fix the issue

**Comment by Ultra-Meloncrafter** [comment]
[onthespot.log](https://github.com/user-attachments/files/19922238/onthespot.log)
@justin025 there you go

**Comment by r4yyy** [comment]
I have a premium Crunchyroll account that I have logged in on and I have not been able to download anything from Crunchyroll either. The download fails after the progress bar reaches 1%. This is what my log looks like. 

[2025-07-06 17:43:09,377 :: gui.main_ui :: qt\mainui.py -> 64:                 run() :: ERROR] -> Unknown Exception for {'local_id': 'GJWU2J0ZP/the-pottery-club-of-endless-mysteries-0', 'item_service': 'crunchyroll', 'item_type': 'episode', 'item_id': 'GJWU2J0ZP/the-pottery-club-of-endless-mysteries', 'parent_category': 'show'}: invalid literal for int() with base 10: 'PG'
Traceback: Traceback (most recent call last):
  File "qt\mainui.py", line 55, in run
  File "api\crunchyroll.py", line 258, in crunchyroll_get_episode_metadata
ValueError: invalid literal for int() with base 10: 'PG'

[2025-07-06 17:43:09,450 :: utils :: utils.py -> 67:           make_call() :: INFO] -> Request status error 403: https://static.crunchyroll.com/copyright/GD9UV23KX.json
[2025-07-06 17:43:09,450 :: gui.main_ui :: qt\mainui.py -> 64:                 run() :: ERROR] -> Unknown Exception for {'local_id': 'GD9UV23KX/supersized--cultural-festival-0', 'item_service': 'crunchyroll', 'item_type': 'episode', 'item_id': 'GD9UV23KX/supersized--cultural-festival', 'parent_category': 'show'}: invalid literal for int() with base 10: 'PG'
Traceback: Traceback (most recent call last):
  File "qt\mainui.py", line 55, in run
  File "api\crunchyroll.py", line 258, in crunchyroll_get_episode_metadata
ValueError: invalid literal for int() with base 10: 'PG'

[2025-07-06 17:43:09,450 :: gui.main_ui :: qt\mainui.py -> 64:                 run() :: ERROR] -> Unknown Exception for {'local_id': 'GD9UV23KX/supersized--cultural-festival-0', 'item_service': 'crunchyroll', 'item_type': 'episode', 'item_id': 'GD9UV23KX/supersized--cultural-festival', 'parent_category': 'show'}: invalid literal for int() with base 10: 'PG'
Traceback: Traceback (most recent call last):
  File "qt\mainui.py", line 55, in run
  File "api\crunchyroll.py", line 258, in crunchyroll_get_episode_metadata
ValueError: invalid literal for int() with base 10: 'PG'

**Comment by justin025** [comment]
they seem to be only metadata errors can you try the latest commit here https://github.com/justin025/onthespot/actions/runs/16843951764

**Comment by justin025** [comment]
should be fixed in the latest release, feel free to reopen if not https://github.com/justin025/onthespot/releases/tag/v1.1.1

**Comment by Ultra-Meloncrafter** [comment]
The Problem still happens and the downloads instantly failed, both with 1.1.1 and 1.1.2

**Comment by AAMBIENTT** [comment]
Issues still occur. 1.1.2

[2025-10-09 10:28:02,429 :: gui :: gui.py -> 48:                main() :: INFO] -> OnTheSpot Version: v1.1.2
[2025-10-09 10:28:02,692 :: gui.main_ui :: qt\mainui.py -> 94:            __init__() :: INFO] -> Initialising main window, logging session : aaa9f305-c31c-41c6-9203-83341135a980
[2025-10-09 10:28:02,692 :: gui.main_ui :: qt\mainui.py -> 94:            __init__() :: INFO] -> Initialising main window, logging session : aaa9f305-c31c-41c6-9203-83341135a980
[2025-10-09 10:28:02,692 :: gui.main_ui :: qt\mainui.py -> 97:            __init__() :: INFO] -> Loading configurations..
[2025-10-09 10:28:02,692 :: gui.main_ui :: qt\mainui.py -> 97:            __init__() :: INFO] -> Loading configurations..
[2025-10-09 10:28:02,800 :: downloader :: downloader.py -> 77:               start() :: INFO] -> Starting Download Worker
[2025-10-09 10:28:02,800 :: api.bandcamp :: api\bandcamp.py -> 13: bandcamp_login_user() :: INFO] -> Logging into Bandcamp account...
[2025-10-09 10:28:02,801 :: gui.main_ui :: qt\mainui.py -> 131:            __init__() :: INFO] -> Main window init completed !
[2025-10-09 10:28:02,801 :: gui.main_ui :: qt\mainui.py -> 131:            __init__() :: INFO] -> Main window init completed !
[2025-10-09 10:28:02,856 :: api.deezer :: api\deezer.py -> 232:   deezer_login_user() :: INFO] -> Logging into Deezer account...
[2025-10-09 10:28:03,477 :: api.soundcloud :: api\soundcloud.py -> 32:soundcloud_login_user() :: INFO] -> Logging into Soundcloud account...
[2025-10-09 10:28:04,047 :: api.youtube_music :: api\youtube_music.py -> 13:youtube_music_login_user() :: INFO] -> Logging into Youtube account...
[2025-10-09 10:28:05,773 :: gui.main_ui :: qt\mainui.py -> 336:  fill_account_table() :: INFO] -> Accounts table was populated !
[2025-10-09 10:28:05,773 :: gui.main_ui :: qt\mainui.py -> 336:  fill_account_table() :: INFO] -> Accounts table was populated !
[2025-10-09 10:29:36,630 :: search :: search.py -> 28:  get_search_results() :: INFO] -> Search clicked with value with url https://www.crunchyroll.com/series/GR24GX896/kabaneri-of-the-iron-fortress
[2025-10-09 10:29:36,806 :: parse_item :: parse_item.py -> 170:       parsingworker() :: INFO] -> Parsing: {'item_url': 'https://www.crunchyroll.com/series/GR24GX896/kabaneri-of-the-iron-fortress', 'item_service': 'crunchyroll', 'item_type': 'show', 'item_id': 'GR24GX896/kabaneri-of-the-iron-fortress'}
[2025-10-09 10:29:38,067 :: utils :: utils.py -> 67:           make_call() :: INFO] -> Request status error 403: https://static.crunchyroll.com/copyright/G6G5E1336.json
[2025-10-09 10:29:38,438 :: utils :: utils.py -> 67:           make_call() :: INFO] -> Request status error 403: https://static.crunchyroll.com/copyright/G6G5E1336.json
[2025-10-09 10:29:38,542 :: utils :: utils.py -> 67:           make_call() :: INFO] -> Request status error 403: https://static.crunchyroll.com/copyright/G6EXG5EVR.json
[2025-10-09 10:29:38,554 :: downloader :: downloader.py -> 522:                 run() :: ERROR] -> 400 Response: {"error":40016,"reason":"Outdated Token"}
[2025-10-09 10:29:38,915 :: utils :: utils.py -> 67:           make_call() :: INFO] -> Request status error 403: https://static.crunchyroll.com/copyright/GY9V1PGVR.json
[2025-10-09 10:29:39,470 :: utils :: utils.py -> 67:           make_call() :: INFO] -> Request status error 403: https://static.crunchyroll.com/copyright/GY4PE9216.json
[2025-10-09 10:29:39,691 :: downloader :: downloader.py -> 766:                 run() :: ERROR] -> Unknown Exception: Command '['C:\\Users\\\\AppData\\Local\\Temp\\_MEI48962\\onthespot\\bin\\ffmpeg\\ffmpeg.exe', '-metadata', 'title=Frightened Corpse', '-metadata', 'copyright=', '-metadata', 'description=The immortal monsters known as Kabane have attacked Aragane Station. Ikoma, a boy who lives in Aragane Station, ran against the waves of terrified civilians to fight against Kabane using a weapon he has been secretly developing - the Piercing gun.', '-metadata', 'show=Kabaneri of the Iron Fortress', '-metadata', 'episode_id=1', '-metadata', 'tvsn=1', '-loglevel', 'error', '-hide_banner', '-nostats', '-c', 'copy', 'Z:\\Shows\\Kabaneri of the Iron Fortress\\Season 1\\~1. Frightened Corpse.mkv']' returned non-zero exit status 4294967274.
Traceback: Traceback (most recent call last):
  File "downloader.py", line 746, in run
  File "utils.py", line 297, in convert_video_format
  File "subprocess.py", line 413, in check_call
subprocess.CalledProcessError: Command '['C:\\Users\\\\AppData\\Local\\Temp\\_MEI48962\\onthespot\\bin\\ffmpeg\\ffmpeg.exe', '-metadata', 'title=Frightened Corpse', '-metadata', 'copyright=', '-metadata', 'description=The immortal monsters known as Kabane have attacked Aragane Station. Ikoma, a boy who lives in Aragane Station, ran against the waves of terrified civilians to fight against Kabane using a weapon he has been secretly developing - the Piercing gun.', '-metadata', 'show=Kabaneri of the Iron Fortress', '-metadata', 'episode_id=1', '-metadata', 'tvsn=1', '-loglevel', 'error', '-hide_banner', '-nostats', '-c', 'copy', 'Z:\\Shows\\Kabaneri of the Iron Fortress\\Season 1\\~1. Frightened Corpse.mkv']' returned non-zero exit status 4294967274.

[2025-10-09 10:29:39,923 :: utils :: utils.py -> 67:           make_call() :: INFO] -> Request status error 403: https://static.crunchyroll.com/copyright/GYJ0XQ726.json
[2025-10-09 10:29:40,456 :: utils :: utils.py -> 67:           make_call() :: INFO] -> Request status error 403: https://static.crunchyroll.com/copyright/GYKE45DMY.json
[2025-10-09 10:29:40,888 :: utils :: utils.py -> 67:           make_call() :: INFO] -> Request status error 403: https://static.crunchyroll.com/copyright/G6VD5N946.json
[2025-10-09 10:29:41,326 :: utils :: utils.py -> 67:           make_call() :: INFO] -> Request status error 403: https://static.crunchyroll.com/copyright/GYP5M879Y.json
[2025-10-09 10:29:41,855 :: utils :: utils.py -> 67:           make_call() :: INFO] -> Request status error 403: https://static.crunchyroll.com/copyright/GR8D4V27R.json
[2025-10-09 10:29:42,374 :: utils :: utils.py -> 67:           make_call() :: INFO] -> Request status error 403: https://static.crunchyroll.com/copyright/G6DKWQ03R.json
[2025-10-09 10:29:42,873 :: utils :: utils.py -> 67:           make_call() :: INFO] -> Request status error 403: https://static.crunchyroll.com/copyright/GY5P7V27Y.json
[2025-10-09 10:29:42,939 :: utils :: utils.py -> 67:           make_call() :: INFO] -> Request status error 403: https://static.crunchyroll.com/copyright/G6EXG5EVR.json
[2025-10-09 10:29:43,027 :: downloader :: downloader.py -> 522:                 run() :: ERROR] -> 400 Response: {"error":40016,"reason":"Outdated Token"}
[2025-10-09 10:29:43,053 :: downloader :: downloader.py -> 766:                 run() :: ERROR] -> Unknown Exception: Command '['C:\\Users\\\\AppData\\Local\\Temp\\_MEI48962\\onthespot\\bin\\ffmpeg\\ffmpeg.exe', '-metadata', 'title=Never-Ending Darkness', '-metadata', 'copyright=', '-metadata', 'description=Ikoma somehow survives and heads toward the last Hayajiro left in Kenkin Station, the Kotetsujyo. Meanwhile, Ayame and her people were left behind to fend off the Kabane when a young girl named Mumei appears before them.', '-metadata', 'show=Kabaneri of the Iron Fortress', '-metadata', 'episode_id=2', '-metadata', 'tvsn=1', '-loglevel', 'error', '-hide_banner', '-nostats', '-c', 'copy', 'Z:\\Shows\\Kabaneri of the Iron Fortress\\Season 1\\~2. Never-Ending Darkness.mkv']' returned non-zero exit status 4294967274.
Traceback: Traceback (most recent call last):
  File "downloader.py", line 746, in run
  File "utils.py", line 297, in convert_video_format
  File "subprocess.py", line 413, in check_call
subprocess.CalledProcessError: Command '['C:\\Users\\\\AppData\\Local\\Temp\\_MEI48962\\onthespot\\bin\\ffmpeg\\ffmpeg.exe', '-metadata', 'title=Never-Ending Darkness', '-metadata', 'copyright=', '-metadata', 'description=Ikoma somehow survives and heads toward the last Hayajiro left in Kenkin Station, the Kotetsujyo. Meanwhile, Ayame and her people were left behind to fend off the Kabane when a young girl named Mumei appears before them.', '-metadata', 'show=Kabaneri of the Iron Fortress', '-metadata', 'episode_id=2', '-metadata', 'tvsn=1', '-loglevel', 'error', '-hide_banner', '-nostats', '-c', 'copy', 'Z:\\Shows\\Kabaneri of the Iron Fortress\\Season 1\\~2. Never-Ending Darkness.mkv']' returned non-zero exit status 4294967274.

[2025-10-09 10:29:43,322 :: utils :: utils.py -> 67:           make_call() :: INFO] -> Request status error 403: https://static.crunchyroll.com/copyright/GRG5EGN3R.json
[2025-10-09 10:29:43,746 :: utils :: utils.py -> 67:           make_call() :: INFO] -> Request status error 403: https://static.crunchyroll.com/copyright/GR0XPDJ0Y.json
[2025-10-09 10:29:44,286 :: utils :: utils.py -> 67:           make_call() :: INFO] -> Request status error 403: https://static.crunchyroll.com/copyright/GR790PW36.json
[2025-10-09 10:29:46,205 :: utils :: utils.py -> 67:           make_call() :: INFO] -> Request status error 403: https://static.crunchyroll.com/copyright/GY9V1PGVR.json
[2025-10-09 10:29:46,296 :: downloader :: downloader.py -> 522:                 run() :: ERROR] -> 400 Response: {"error":40016,"reason":"Outdated Token"}
[2025-10-09 10:29:46,320 :: downloader :: downloader.py -> 766:                 run() :: ERROR] -> Unknown Exception: Command '['C:\\Users\\\\AppData\\Local\\Temp\\_MEI48962\\onthespot\\bin\\ffmpeg\\ffmpeg.exe', '-metadata', 'title=Prayer Offer', '-metadata', 'copyright=', '-metadata', "description=Having escaped Kenkin Station, the Kotetsujyo heads for Kongokaku, the Shogunate's fortress. However, the people on the Kotetsujyo quickly turn against Ikoma and Mumei and attempt to drive them off the train.", '-metadata', 'show=Kabaneri of the Iron Fortress', '-metadata', 'episode_id=3', '-metadata', 'tvsn=1', '-loglevel', 'error', '-hide_banner', '-nostats', '-c', 'copy', 'Z:\\Shows\\Kabaneri of the Iron Fortress\\Season 1\\~3. Prayer Offer.mkv']' returned non-zero exit status 4294967274.
Traceback: Traceback (most recent call last):
  File "downloader.py", line 746, in run
  File "utils.py", line 297, in convert_video_format
  File "subprocess.py", line 413, in check_call
subprocess.CalledProcessError: Command '['C:\\Users\\\\AppData\\Local\\Temp\\_MEI48962\\onthespot\\bin\\ffmpeg\\ffmpeg.exe', '-metadata', 'title=Prayer Offer', '-metadata', 'copyright=', '-metadata', "description=Having escaped Kenkin Station, the Kotetsujyo heads for Kongokaku, the Shogunate's fortress. However, the people on the Kotetsujyo quickly turn against Ikoma and Mumei and attempt to drive them off the train.", '-metadata', 'show=Kabaneri of the Iron Fortress', '-metadata', 'episode_id=3', '-metadata', 'tvsn=1', '-loglevel', 'error', '-hide_banner', '-nostats', '-c', 'copy', 'Z:\\Shows\\Kabaneri of the Iron Fortress\\Season 1\\~3. Prayer Offer.mkv']' returned non-zero exit status 4294967274.

[2025-10-09 10:29:49,558 :: utils :: utils.py -> 67:           make_call() :: INFO] -> Request status error 403: https://static.crunchyroll.com/copyright/GY4PE9216.json
[2025-10-09 10:29:49,646 :: downloader :: downloader.py -> 522:                 run() :: ERROR] -> 400 Response: {"error":40016,"reason":"Outdated Token"}
[2025-10-09 10:29:49,671 :: downloader :: downloader.py -> 766:                 run() :: ERROR] -> Unknown Exception: Command '['C:\\Users\\\\AppData\\Local\\Temp\\_MEI48962\\onthespot\\bin\\ffmpeg\\ffmpeg.exe', '-metadata', 'title=Flowing Blood', '-metadata', 'copyright=', '-metadata', 'description=The other people lock Ikoma and Mumei into the rear car, despite them being two of the best fighters. Just then, the Kabane attack! And among them is a Wazatori, a Kabane that has the ability to learn and become stronger with each battle.', '-metadata', 'show=Kabaneri of the Iron Fortress', '-metadata', 'episode_id=4', '-metadata', 'tvsn=1', '-loglevel', 'error', '-hide_banner', '-nostats', '-c', 'copy', 'Z:\\Shows\\Kabaneri of the Iron Fortress\\Season 1\\~4. Flowing Blood.mkv']' returned non-zero exit status 4294967274.
Traceback: Traceback (most recent call last):
  File "downloader.py", line 746, in run
  File "utils.py", line 297, in convert_video_format
  File "subprocess.py", line 413, in check_call
subprocess.CalledProcessError: Command '['C:\\Users\\\\AppData\\Local\\Temp\\_MEI48962\\onthespot\\bin\\ffmpeg\\ffmpeg.exe', '-metadata', 'title=Flowing Blood', '-metadata', 'copyright=', '-metadata', 'description=The other people lock Ikoma and Mumei into the rear car, despite them being two of the best fighters. Just then, the Kabane attack! And among them is a Wazatori, a Kabane that has the ability to learn and become stronger with each battle.', '-metadata', 'show=Kabaneri of the Iron Fortress', '-metadata', 'episode_id=4', '-metadata', 'tvsn=1', '-loglevel', 'error', '-hide_banner', '-nostats', '-c', 'copy', 'Z:\\Shows\\Kabaneri of the Iron Fortress\\Season 1\\~4. Flowing Blood.mkv']' returned non-zero exit status 4294967274.

[2025-10-09 10:29:52,816 :: utils :: utils.py -> 67:           make_call() :: INFO] -> Request status error 403: https://static.crunchyroll.com/copyright/GYJ0XQ726.json
[2025-10-09 10:29:52,905 :: downloader :: downloader.py -> 522:                 run() :: ERROR] -> 400 Response: {"error":40016,"reason":"Outdated Token"}
[2025-10-09 10:29:52,930 :: downloader :: downloader.py -> 766:                 run() :: ERROR] -> Unknown Exception: Command '['C:\\Users\\\\AppData\\Local\\Temp\\_MEI48962\\onthespot\\bin\\ffmpeg\\ffmpeg.exe', '-metadata', 'title=Inescapable Darkness', '-metadata', 'copyright=', '-metadata', "description=The Kotetsujyo picks up survivors from Yatsushiro Station which has been destroyed by the Kabane. Among the survivors is Enoku, an old friend of Mumei's. He points out to Mumei how weak she's become as she's grown closer to the people of the Kotetsujyo.", '-metadata', 'show=Kabaneri of the Iron Fortress', '-metadata', 'episode_id=5', '-metadata', 'tvsn=1', '-loglevel', 'error', '-hide_banner', '-nostats', '-c', 'copy', 'Z:\\Shows\\Kabaneri of the Iron Fortress\\Season 1\\~5. Inescapable Darkness.mkv']' returned non-zero exit status 4294967274.
Traceback: Traceback (most recent call last):
  File "downloader.py", line 746, in run
  File "utils.py", line 297, in convert_video_format
  File "subprocess.py", line 413, in check_call
subprocess.CalledProcessError: Command '['C:\\Users\\\\AppData\\Local\\Temp\\_MEI48962\\onthespot\\bin\\ffmpeg\\ffmpeg.exe', '-metadata', 'title=Inescapable Darkness', '-metadata', 'copyright=', '-metadata', "description=The Kotetsujyo picks up survivors from Yatsushiro Station which has been destroyed by the Kabane. Among the survivors is Enoku, an old friend of Mumei's. He points out to Mumei how weak she's become as she's grown closer to the people of the Kotetsujyo.", '-metadata', 'show=Kabaneri of the Iron Fortress', '-metadata', 'episode_id=5', '-metadata', 'tvsn=1', '-loglevel', 'error', '-hide_banner', '-nostats', '-c', 'copy', 'Z:\\Shows\\Kabaneri of the Iron Fortress\\Season 1\\~5. Inescapable Darkness.mkv']' returned non-zero exit status 4294967274.
