### ISSUE TITLE
All downloads fail (Error: Failed fetching audio key)

### ISSUE THREAD

**Issue by Comathoss** [justin025/onthespot#234]
### Operating System

Windows

### Bug Description

Every track of the playlist gets the same error after 1% download. I tried changing the download delay to 15 and that didn't help, and I doubt it's a DNS problem, as some noted on other similar bug reports. Been getting the error since yesterday, but before that it downloaded a track from soundcloud without issues, it's spotify-specific. Log attached. 
[onthespot.log](https://github.com/user-attachments/files/23384980/onthespot.log)

**Comment by Driftix-V** [comment]
Hey also here! the same,pls fix fast :] OTS 1.1.2, using spotify premium

**Comment by benjaminfrombe** [comment]
Same here ...

**Comment by webl117** [comment]
same

**Comment by justin025** [comment]
Should be fixed in the latest update

**Comment by Comathoss** [comment]
> Should be fixed in the latest update

Nope, sadly still getting the error 

[onthespot.log](https://github.com/user-attachments/files/23997581/onthespot.log)

**Comment by moddroid94** [comment]
> > Should be fixed in the latest update
> 
> Nope, sadly still getting the error
> 
> [onthespot.log](https://github.com/user-attachments/files/23997581/onthespot.log)

are you using a free account?

**Comment by Comathoss** [comment]
> > > Should be fixed in the latest update
> > 
> > 
> > Nope, sadly still getting the error
> > [onthespot.log](https://github.com/user-attachments/files/23997581/onthespot.log)
> 
> are you using a free account?

Yeah?

**Comment by moddroid94** [comment]
> > > > Should be fixed in the latest update
> > > 
> > > 
> > > Nope, sadly still getting the error
> > > [onthespot.log](https://github.com/user-attachments/files/23997581/onthespot.log)
> > 
> > 
> > are you using a free account?
> 
> Yeah?

the upstream tool we use stopped supporting free accounts, so until someone finds a new way to get the keys we cannot fix it.

**Comment by Comathoss** [comment]
> > > Should be fixed in the latest update
> > 
> > 
> > Nope, sadly still getting the error
> > [onthespot.log](https://github.com/user-attachments/files/23997581/onthespot.log)
> 
> are you using a free account?

Alright, I got a premium account, and I'm still getting that error...

[onthespot.log](https://github.com/user-attachments/files/24018693/onthespot.log)

**Comment by moddroid94** [comment]
@Comathoss I don't know at this point, if that's the last version (1.1.3) and you're sure that's a premium account then I don't know. 

I may be seeing some strange behavior in the log but that's a case I've not encountered yet.

It may be fixed with the latest metadata endpoint,  but that's totally a guess.
